# Generated by Django 2.0.1 on 2018-04-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='poster',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='respondent',
            new_name='user',
        ),
    ]
