# Generated by Django 2.0.1 on 2018-04-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20180416_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_date',
            new_name='date_posted',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='post_date',
            new_name='date_posted',
        ),
    ]
