# Generated by Django 2.0.1 on 2018-04-16 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20180416_1238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='Comment',
        ),
    ]
